version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:24.6.1

dependencies:
  # python_interpreter:
  #   package_system: python3
  # ansible_core:
  #   package_pip: ansible-core
  # ansible_runner:
  #   package_pip: ansible-runner
  # system:
  # - openssh-clients
  # - sshpass
  galaxy:
    collections:
    - name: crowdstrike.falcon
